const idPathParam = {
  name: "id",
  in: "path",
  required: true,
  schema: { type: "string" },
} as const;

const characterIdPathParam = {
  name: "characterId",
  in: "path",
  required: true,
  schema: { type: "string" },
} as const;

const authSecurity = [{ bearerAuth: [] }] as const;

export const openApiDocument = {
  openapi: "3.0.3",
  info: {
    title: "GOB Backend API",
    version: "1.4.0",
    description:
      "API para autenticacao, personagens, inventario, gameplay, administracao de conteudo, loja, pagamentos e recompensas do jogo.",
  },
  servers: [{ url: "http://localhost:5000", description: "Desenvolvimento local" }],
  tags: [
    { name: "Health", description: "Operacao e disponibilidade da API" },
    { name: "Auth", description: "Autenticacao e sessao" },
    { name: "Users", description: "Perfil do usuario" },
    { name: "Characters", description: "Gestao de personagens e classes" },
    { name: "Inventory", description: "Inventario e equipamentos" },
    { name: "Gameplay", description: "Fluxos jogaveis e combate" },
    { name: "Admin", description: "Montagem de conteudo do jogo" },
    { name: "Rewards", description: "Resgate de recompensas" },
    { name: "Transactions", description: "Historico de transacoes" },
    { name: "Shop", description: "Loja e pagamentos" },
  ],
  components: {
    securitySchemes: {
      bearerAuth: { type: "http", scheme: "bearer", bearerFormat: "JWT" },
    },
    responses: {
      BadRequest: { description: "Payload invalido" },
      Unauthorized: { description: "Nao autenticado" },
      Forbidden: { description: "Sem permissao" },
      NotFound: { description: "Recurso nao encontrado" },
      Conflict: { description: "Conflito de estado ou duplicidade" },
    },
    schemas: {
      ErrorResponse: {
        type: "object",
        properties: {
          success: { type: "boolean" },
          error: {
            type: "object",
            properties: {
              code: { type: "string" },
              message: { type: "string" },
            },
          },
        },
      },
      UserPublic: {
        type: "object",
        properties: {
          id: { type: "string" },
          nome: { type: "string" },
          email: { type: "string", format: "email" },
          role: { type: "string", enum: ["PLAYER", "ADMIN"] },
        },
      },
      Class: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          modifier: { type: "string" },
          description: { type: "string" },
          passive: { type: "string" },
        },
      },
      Character: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          level: { type: "integer" },
          xp: { type: "integer" },
          classId: { type: "string" },
          inventoryId: { type: "string", nullable: true },
        },
      },
      Monster: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          level: { type: "integer" },
          health: { type: "integer" },
          attack: { type: "integer" },
          defense: { type: "integer" },
          experience: { type: "integer" },
        },
      },
      Bounty: {
        type: "object",
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          monsterId: { type: "string" },
          recommendedLevel: { type: "integer" },
          difficulty: { type: "string", enum: ["EASY", "MEDIUM", "HARD", "ELITE"] },
          reward: { type: "integer" },
          rewardXp: { type: "integer" },
          status: { type: "string" },
          isActive: { type: "boolean" },
          timeLimit: { type: "string", format: "date-time" },
          monster: { $ref: "#/components/schemas/Monster" },
        },
      },
      MissionDefinition: {
        type: "object",
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          difficulty: { type: "string", enum: ["EASY", "MEDIUM", "HARD", "ELITE"] },
          recommendedLevel: { type: "integer" },
          enemyName: { type: "string" },
          enemyLevel: { type: "integer" },
          rewardXp: { type: "integer" },
          rewardCoins: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
      TrainingDefinition: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          trainingType: { type: "string" },
          xpReward: { type: "integer" },
          coinsReward: { type: "integer" },
          cooldownSeconds: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
      NpcDefinition: {
        type: "object",
        properties: {
          id: { type: "string" },
          name: { type: "string" },
          role: { type: "string" },
          interactionType: { type: "string" },
          dialogue: { type: "string" },
          xpReward: { type: "integer" },
          coinsReward: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
      AuthSuccessResponse: {
        type: "object",
        properties: {
          success: { type: "boolean" },
          message: { type: "string" },
          token: { type: "string" },
          user: { $ref: "#/components/schemas/UserPublic" },
        },
      },
      RegisterRequest: {
        type: "object",
        required: ["nome", "email", "senha"],
        properties: {
          nome: { type: "string" },
          email: { type: "string", format: "email" },
          senha: { type: "string" },
        },
      },
      LoginRequest: {
        type: "object",
        required: ["email", "senha"],
        properties: {
          email: { type: "string", format: "email" },
          senha: { type: "string" },
        },
      },
      CreateCharacterRequest: {
        type: "object",
        required: ["name"],
        properties: {
          name: { type: "string" },
          classId: { type: "string" },
        },
      },
      UpdateCharacterRequest: {
        type: "object",
        properties: { name: { type: "string" } },
      },
      UpdateCharacterProgressRequest: {
        type: "object",
        properties: {
          xp: { type: "integer" },
          level: { type: "integer" },
          lastCheckpoint: { type: "string" },
        },
      },
      UpdateCharacterPositionRequest: {
        type: "object",
        properties: {
          posX: { type: "number" },
          posY: { type: "number" },
          posZ: { type: "number" },
          lastCheckpoint: { type: "string" },
        },
      },
      ClaimRewardRequest: {
        type: "object",
        required: ["characterId", "claimKey", "type", "value"],
        properties: {
          characterId: { type: "string" },
          claimKey: { type: "string" },
          type: { type: "string", enum: ["COINS", "XP"] },
          value: { type: "integer" },
          metadata: { type: "string" },
        },
      },
      PurchaseRequest: {
        type: "object",
        required: ["characterId", "productId", "quantity"],
        properties: {
          characterId: { type: "string" },
          productId: { type: "string" },
          quantity: { type: "integer" },
        },
      },
      PaymentOrderRequest: {
        type: "object",
        required: ["characterId", "productId", "quantity"],
        properties: {
          characterId: { type: "string" },
          productId: { type: "string" },
          quantity: { type: "integer" },
          provider: { type: "string" },
        },
      },
      PaymentWebhookRequest: {
        type: "object",
        required: ["status"],
        properties: {
          orderId: { type: "string" },
          providerReference: { type: "string" },
          providerPaymentId: { type: "string" },
          status: { type: "string", enum: ["PAID", "FAILED", "CANCELED"] },
          failureReason: { type: "string" },
        },
      },
      BountyActionRequest: {
        type: "object",
        required: ["bountyId"],
        properties: { bountyId: { type: "string" } },
      },
      MissionActionRequest: {
        type: "object",
        required: ["missionId"],
        properties: { missionId: { type: "string" } },
      },
      TrainingActionRequest: {
        type: "object",
        required: ["trainingId"],
        properties: { trainingId: { type: "string" } },
      },
      NpcActionRequest: {
        type: "object",
        required: ["npcId"],
        properties: { npcId: { type: "string" } },
      },
      MarketActionRequest: {
        type: "object",
        required: ["action"],
        properties: {
          action: { type: "string", enum: ["barter", "scavenge"] },
        },
      },
      AdminMonsterRequest: {
        type: "object",
        required: ["name", "level", "health", "attack", "defense", "experience"],
        properties: {
          name: { type: "string" },
          level: { type: "integer" },
          health: { type: "integer" },
          attack: { type: "integer" },
          defense: { type: "integer" },
          experience: { type: "integer" },
        },
      },
      AdminBountyRequest: {
        type: "object",
        required: [
          "title",
          "monsterId",
          "recommendedLevel",
          "difficulty",
          "reward",
          "rewardXp",
          "timeLimit",
          "status",
        ],
        properties: {
          title: { type: "string" },
          description: { type: "string" },
          monsterId: { type: "string" },
          recommendedLevel: { type: "integer" },
          difficulty: { type: "string", enum: ["EASY", "MEDIUM", "HARD", "ELITE"] },
          reward: { type: "integer" },
          rewardXp: { type: "integer" },
          timeLimit: { type: "string", format: "date-time" },
          status: { type: "string" },
          isActive: { type: "boolean" },
        },
      },
      AdminMissionRequest: {
        type: "object",
        required: [
          "title",
          "difficulty",
          "recommendedLevel",
          "enemyName",
          "enemyLevel",
          "enemyHealth",
          "enemyAttack",
          "enemyDefense",
          "rewardXp",
          "rewardCoins",
        ],
        properties: {
          title: { type: "string" },
          description: { type: "string" },
          difficulty: { type: "string", enum: ["EASY", "MEDIUM", "HARD", "ELITE"] },
          recommendedLevel: { type: "integer" },
          enemyName: { type: "string" },
          enemyLevel: { type: "integer" },
          enemyHealth: { type: "integer" },
          enemyAttack: { type: "integer" },
          enemyDefense: { type: "integer" },
          rewardXp: { type: "integer" },
          rewardCoins: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
      AdminTrainingRequest: {
        type: "object",
        required: ["name", "trainingType", "xpReward"],
        properties: {
          name: { type: "string" },
          description: { type: "string" },
          trainingType: { type: "string" },
          xpReward: { type: "integer" },
          coinsReward: { type: "integer" },
          cooldownSeconds: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
      AdminNpcRequest: {
        type: "object",
        required: ["name", "role", "interactionType"],
        properties: {
          name: { type: "string" },
          role: { type: "string" },
          interactionType: { type: "string" },
          description: { type: "string" },
          dialogue: { type: "string" },
          xpReward: { type: "integer" },
          coinsReward: { type: "integer" },
          isActive: { type: "boolean" },
        },
      },
    },
  },
  paths: {
    "/health": { get: { tags: ["Health"], summary: "Healthcheck simples", responses: { "200": { description: "OK" } } } },
    "/ready": { get: { tags: ["Health"], summary: "Readiness com banco", responses: { "200": { description: "OK" } } } },
    "/api/v1/auth/register": {
      post: {
        tags: ["Auth"],
        summary: "Registrar usuario",
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/RegisterRequest" } } } },
        responses: { "201": { description: "Usuario criado" }, "400": { $ref: "#/components/responses/BadRequest" }, "409": { $ref: "#/components/responses/Conflict" } },
      },
    },
    "/api/v1/auth/login": {
      post: {
        tags: ["Auth"],
        summary: "Autenticar usuario",
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/LoginRequest" } } } },
        responses: { "200": { description: "Login realizado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/v1/auth/me": { get: { tags: ["Auth"], summary: "Obter usuario autenticado", security: authSecurity, responses: { "200": { description: "Usuario autenticado" }, "401": { $ref: "#/components/responses/Unauthorized" } } } },
    "/api/v1/users/me/profile": {
      get: { tags: ["Users"], summary: "Obter perfil", security: authSecurity, responses: { "200": { description: "Perfil retornado" }, "401": { $ref: "#/components/responses/Unauthorized" } } },
      patch: { tags: ["Users"], summary: "Atualizar perfil", security: authSecurity, responses: { "200": { description: "Perfil atualizado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "409": { $ref: "#/components/responses/Conflict" } } },
    },
    "/api/v1/characters/classes": { get: { tags: ["Characters"], summary: "Listar classes", security: authSecurity, responses: { "200": { description: "Classes retornadas" }, "401": { $ref: "#/components/responses/Unauthorized" } } } },
    "/api/v1/characters": {
      get: { tags: ["Characters"], summary: "Listar personagens", security: authSecurity, responses: { "200": { description: "Lista de personagens" }, "401": { $ref: "#/components/responses/Unauthorized" } } },
      post: {
        tags: ["Characters"],
        summary: "Criar personagem",
        security: authSecurity,
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/CreateCharacterRequest" } } } },
        responses: { "201": { description: "Personagem criado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" } },
      },
    },
    "/api/v1/characters/{id}": {
      get: { tags: ["Characters"], summary: "Buscar personagem por id", security: authSecurity, parameters: [idPathParam], responses: { "200": { description: "Personagem encontrado" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } } },
      put: {
        tags: ["Characters"],
        summary: "Atualizar nome do personagem",
        security: authSecurity,
        parameters: [idPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateCharacterRequest" } } } },
        responses: { "200": { description: "Personagem atualizado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } },
      },
      delete: { tags: ["Characters"], summary: "Excluir personagem", security: authSecurity, parameters: [idPathParam], responses: { "200": { description: "Personagem removido" } } },
    },
    "/api/v1/characters/{id}/summary": { get: { tags: ["Characters"], summary: "Resumo do personagem", security: authSecurity, parameters: [idPathParam], responses: { "200": { description: "Resumo retornado" } } } },
    "/api/v1/characters/{id}/progress": {
      patch: {
        tags: ["Characters"],
        summary: "Atualizar progresso",
        security: authSecurity,
        parameters: [idPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateCharacterProgressRequest" } } } },
        responses: { "200": { description: "Progresso atualizado" } },
      },
    },
    "/api/v1/characters/{id}/position": {
      patch: {
        tags: ["Characters"],
        summary: "Atualizar posicao",
        security: authSecurity,
        parameters: [idPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/UpdateCharacterPositionRequest" } } } },
        responses: { "200": { description: "Posicao atualizada" } },
      },
    },
    "/api/v1/inventory/characters/{characterId}": { get: { tags: ["Inventory"], summary: "Obter inventario", security: authSecurity, parameters: [characterIdPathParam], responses: { "200": { description: "Inventario retornado" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } } } },
    "/api/v1/inventory/characters/{characterId}/wallet": { get: { tags: ["Inventory"], summary: "Obter carteira", security: authSecurity, parameters: [characterIdPathParam], responses: { "200": { description: "Carteira retornada" } } } },
    "/api/v1/inventory/characters/{characterId}/items/{itemId}/use": { post: { tags: ["Inventory"], summary: "Usar item", security: authSecurity, parameters: [characterIdPathParam, { name: "itemId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Item usado" } } } },
    "/api/v1/inventory/characters/{characterId}/equipments/{equipmentId}/equip": { post: { tags: ["Inventory"], summary: "Equipar equipamento", security: authSecurity, parameters: [characterIdPathParam, { name: "equipmentId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Equipamento equipado" } } } },
    "/api/v1/inventory/characters/{characterId}/equipments/{equipmentId}/unequip": { post: { tags: ["Inventory"], summary: "Desequipar equipamento", security: authSecurity, parameters: [characterIdPathParam, { name: "equipmentId", in: "path", required: true, schema: { type: "string" } }], responses: { "200": { description: "Equipamento desequipado" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/gameplay/journey": { get: { tags: ["Gameplay"], summary: "Obter jornada e opcoes", responses: { "200": { description: "Jornada retornada" } } } },
    "/api/v1/gameplay/monsters": { get: { tags: ["Gameplay"], summary: "Listar monstros", responses: { "200": { description: "Monstros retornados" } } } },
    "/api/v1/gameplay/bounties": { get: { tags: ["Gameplay"], summary: "Listar bounties ativas", responses: { "200": { description: "Bounties retornadas" } } } },
    "/api/v1/gameplay/missions": { get: { tags: ["Gameplay"], summary: "Listar missoes ativas", responses: { "200": { description: "Missoes retornadas" } } } },
    "/api/v1/gameplay/trainings": { get: { tags: ["Gameplay"], summary: "Listar treinamentos ativos", responses: { "200": { description: "Treinamentos retornados" } } } },
    "/api/v1/gameplay/npcs": { get: { tags: ["Gameplay"], summary: "Listar NPCs ativos", responses: { "200": { description: "NPCs retornados" } } } },
    "/api/v1/gameplay/characters/{characterId}/actions/bounty-hunt": {
      post: {
        tags: ["Gameplay"],
        summary: "Executar bounty hunt",
        security: authSecurity,
        parameters: [characterIdPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/BountyActionRequest" } } } },
        responses: { "200": { description: "Bounty hunt executada" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" }, "409": { $ref: "#/components/responses/Conflict" } },
      },
    },
    "/api/v1/gameplay/characters/{characterId}/actions/missions": {
      post: {
        tags: ["Gameplay"],
        summary: "Executar missao",
        security: authSecurity,
        parameters: [characterIdPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MissionActionRequest" } } } },
        responses: { "200": { description: "Missao executada" } },
      },
    },
    "/api/v1/gameplay/characters/{characterId}/actions/training": {
      post: {
        tags: ["Gameplay"],
        summary: "Executar treinamento",
        security: authSecurity,
        parameters: [characterIdPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/TrainingActionRequest" } } } },
        responses: { "200": { description: "Treinamento executado" } },
      },
    },
    "/api/v1/gameplay/characters/{characterId}/actions/npc-interaction": {
      post: {
        tags: ["Gameplay"],
        summary: "Executar interacao com NPC",
        security: authSecurity,
        parameters: [characterIdPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/NpcActionRequest" } } } },
        responses: { "200": { description: "Interacao executada" } },
      },
    },
    "/api/v1/gameplay/characters/{characterId}/actions/market": {
      post: {
        tags: ["Gameplay"],
        summary: "Executar acao de mercado",
        security: authSecurity,
        parameters: [characterIdPathParam],
        requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/MarketActionRequest" } } } },
        responses: { "200": { description: "Acao de mercado executada" } },
      },
    },
    "/api/v1/admin/monsters": {
      get: { tags: ["Admin"], summary: "Listar monstros", security: authSecurity, responses: { "200": { description: "Monstros retornados" }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" } } },
      post: { tags: ["Admin"], summary: "Criar monstro", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminMonsterRequest" } } } }, responses: { "201": { description: "Monstro criado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" } } },
    },
    "/api/v1/admin/monsters/{id}": { patch: { tags: ["Admin"], summary: "Atualizar monstro", security: authSecurity, parameters: [idPathParam], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminMonsterRequest" } } } }, responses: { "200": { description: "Monstro atualizado" }, "401": { $ref: "#/components/responses/Unauthorized" }, "403": { $ref: "#/components/responses/Forbidden" }, "404": { $ref: "#/components/responses/NotFound" } } } },
    "/api/v1/admin/bounties": {
      get: { tags: ["Admin"], summary: "Listar bounties", security: authSecurity, responses: { "200": { description: "Bounties retornadas" } } },
      post: { tags: ["Admin"], summary: "Criar bounty", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminBountyRequest" } } } }, responses: { "201": { description: "Bounty criada" } } },
    },
    "/api/v1/admin/bounties/{id}": { patch: { tags: ["Admin"], summary: "Atualizar bounty", security: authSecurity, parameters: [idPathParam], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminBountyRequest" } } } }, responses: { "200": { description: "Bounty atualizada" } } } },
    "/api/v1/admin/missions": {
      get: { tags: ["Admin"], summary: "Listar missoes", security: authSecurity, responses: { "200": { description: "Missoes retornadas" } } },
      post: { tags: ["Admin"], summary: "Criar missao", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminMissionRequest" } } } }, responses: { "201": { description: "Missao criada" } } },
    },
    "/api/v1/admin/missions/{id}": { patch: { tags: ["Admin"], summary: "Atualizar missao", security: authSecurity, parameters: [idPathParam], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminMissionRequest" } } } }, responses: { "200": { description: "Missao atualizada" } } } },
    "/api/v1/admin/trainings": {
      get: { tags: ["Admin"], summary: "Listar treinamentos", security: authSecurity, responses: { "200": { description: "Treinamentos retornados" } } },
      post: { tags: ["Admin"], summary: "Criar treinamento", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminTrainingRequest" } } } }, responses: { "201": { description: "Treinamento criado" } } },
    },
    "/api/v1/admin/trainings/{id}": { patch: { tags: ["Admin"], summary: "Atualizar treinamento", security: authSecurity, parameters: [idPathParam], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminTrainingRequest" } } } }, responses: { "200": { description: "Treinamento atualizado" } } } },
    "/api/v1/admin/npcs": {
      get: { tags: ["Admin"], summary: "Listar NPCs", security: authSecurity, responses: { "200": { description: "NPCs retornados" } } },
      post: { tags: ["Admin"], summary: "Criar NPC", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminNpcRequest" } } } }, responses: { "201": { description: "NPC criado" } } },
    },
    "/api/v1/admin/npcs/{id}": { patch: { tags: ["Admin"], summary: "Atualizar NPC", security: authSecurity, parameters: [idPathParam], requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/AdminNpcRequest" } } } }, responses: { "200": { description: "NPC atualizado" } } } },
    "/api/v1/rewards/claim": { post: { tags: ["Rewards"], summary: "Resgatar recompensa", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/ClaimRewardRequest" } } } }, responses: { "201": { description: "Recompensa resgatada" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/rewards/characters/{characterId}": { get: { tags: ["Rewards"], summary: "Listar rewards", security: authSecurity, parameters: [characterIdPathParam], responses: { "200": { description: "Claims retornadas" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } } } },
    "/api/v1/transactions/characters/{characterId}": { get: { tags: ["Transactions"], summary: "Historico de transacoes", security: authSecurity, parameters: [characterIdPathParam], responses: { "200": { description: "Historico retornado" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } } } },
    "/api/v1/shop/catalog": { get: { tags: ["Shop"], summary: "Listar catalogo da loja", responses: { "200": { description: "Catalogo retornado" } } } },
    "/api/v1/shop/purchases": { post: { tags: ["Shop"], summary: "Comprar com moeda interna", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/PurchaseRequest" } } } }, responses: { "201": { description: "Compra realizada" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "409": { $ref: "#/components/responses/Conflict" } } } },
    "/api/v1/shop/payment-orders": {
      get: { tags: ["Shop"], summary: "Listar pedidos de pagamento", security: authSecurity, responses: { "200": { description: "Pedidos retornados" }, "401": { $ref: "#/components/responses/Unauthorized" } } },
      post: { tags: ["Shop"], summary: "Criar pedido de pagamento", security: authSecurity, requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/PaymentOrderRequest" } } } }, responses: { "201": { description: "Pedido criado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" } } },
    },
    "/api/v1/shop/webhooks/payments": { post: { tags: ["Shop"], summary: "Processar webhook de pagamento", requestBody: { required: true, content: { "application/json": { schema: { $ref: "#/components/schemas/PaymentWebhookRequest" } } } }, responses: { "200": { description: "Webhook processado" }, "400": { $ref: "#/components/responses/BadRequest" }, "401": { $ref: "#/components/responses/Unauthorized" }, "404": { $ref: "#/components/responses/NotFound" }, "409": { $ref: "#/components/responses/Conflict" } } } },
  },
} as const;
