import { GameplayDifficulty, PrismaClient, ShopProductAssetKind, UserRole } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const adminEmail = process.env.SEED_ADMIN_EMAIL;

  if (adminEmail) {
    const existingAdmin = await prisma.user.findUnique({
      where: { email: adminEmail },
    });

    if (existingAdmin) {
      await prisma.user.update({
        where: { id: existingAdmin.id },
        data: { role: UserRole.ADMIN },
      });
    }
  }

  const classes = [
    {
      name: "Warrior",
      modifier: "STR",
      description: "Especialista em combate corpo a corpo com linha de frente estavel.",
      passive: "Bastiao de Ferro: +10% DEF total.",
    },
    {
      name: "Berserker",
      modifier: "STR",
      description: "Combatente brutal focado em romper defesas com agressividade maxima.",
      passive: "Furia Sanguinea: +15% ATK total e -8% DEF total.",
    },
    {
      name: "Paladin",
      modifier: "STR",
      description: "Guardiao sagrado de alta resistencia, ideal para suportar lutas longas.",
      passive: "Aura de Devocao: +12% HP maximo e +8% DEF total.",
    },
    {
      name: "Mage",
      modifier: "INT",
      description: "Conjurador ofensivo com grande poder bruto em dano arcano.",
      passive: "Fluxo Arcano: +15% ATK total.",
    },
    {
      name: "Sorcerer",
      modifier: "INT",
      description: "Especialista em rajadas instaveis e golpes criticos de energia.",
      passive: "Sobrecarga Mistica: +10% ATK total e +6% crit chance.",
    },
    {
      name: "Cleric",
      modifier: "INT",
      description: "Suporte resistente que converte energia espiritual em sustentacao de combate.",
      passive: "Benção de Vigilia: +8% HP maximo e +10% DEF total.",
    },
    {
      name: "Rogue",
      modifier: "DEX",
      description: "Especialista em mobilidade, oportunismo e finalizacao rapida.",
      passive: "Passos Sombrios: +8% ATK total e +5% crit chance.",
    },
    {
      name: "Ranger",
      modifier: "DEX",
      description: "Combatente versatil com foco em pressao constante e sobrevivencia tatica.",
      passive: "Instinto de Caca: +8% ATK total e +8% HP maximo.",
    },
    {
      name: "Assassin",
      modifier: "DEX",
      description: "Executor letal de burst elevado, feito para vitórias explosivas.",
      passive: "Golpe Fatal: +12% ATK total, +10% crit chance e -6% HP maximo.",
    },
  ];

  for (const characterClass of classes) {
    await prisma.class.upsert({
      where: { name: characterClass.name },
      update: characterClass,
      create: characterClass,
    });
  }

  const monsters = [
    {
      name: "Slime",
      level: 1,
      health: 35,
      attack: 8,
      defense: 3,
      experience: 20,
    },
    {
      name: "Goblin Scout",
      level: 3,
      health: 60,
      attack: 14,
      defense: 6,
      experience: 45,
    },
    {
      name: "Wolf Alpha",
      level: 5,
      health: 95,
      attack: 18,
      defense: 8,
      experience: 75,
    },
    {
      name: "Cavaleiro Corrompido",
      level: 15,
      health: 260,
      attack: 42,
      defense: 19,
      experience: 280,
    },
    {
      name: "Drake de Obsidiana",
      level: 30,
      health: 620,
      attack: 86,
      defense: 37,
      experience: 760,
    },
    {
      name: "Avatar do Despertar",
      level: 30,
      health: 540,
      attack: 90,
      defense: 40,
      experience: 920,
    },
    {
      name: "Titã do Vazio",
      level: 50,
      health: 1280,
      attack: 150,
      defense: 66,
      experience: 1650,
    },
  ];

  const createdMonsters = [];

  for (const monster of monsters) {
    const existingMonster = await prisma.monster.findFirst({
      where: { name: monster.name },
    });

    const savedMonster = existingMonster
      ? await prisma.monster.update({
          where: { id: existingMonster.id },
          data: monster,
        })
      : await prisma.monster.create({
          data: monster,
        });

    createdMonsters.push(savedMonster);
  }

  const bounties = [
    {
      title: "Caçada ao Slime da Fronteira",
      description: "Elimine o slime que bloqueia a rota inicial.",
      monsterName: "Slime",
      recommendedLevel: 1,
      difficulty: GameplayDifficulty.EASY,
      reward: 25,
      rewardXp: 20,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
    },
    {
      title: "Batedor Goblin Procurado",
      description: "Intercepte o batedor goblin antes que entregue informacoes.",
      monsterName: "Goblin Scout",
      recommendedLevel: 3,
      difficulty: GameplayDifficulty.MEDIUM,
      reward: 60,
      rewardXp: 45,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
    },
    {
      title: "Alfa da Floresta Sombria",
      description: "Derrube o lobo alfa e proteja os comerciantes locais.",
      monsterName: "Wolf Alpha",
      recommendedLevel: 5,
      difficulty: GameplayDifficulty.HARD,
      reward: 120,
      rewardXp: 75,
      rewardItemName: "Presa do Alfa",
      rewardItemCategory: "monster_drop",
      rewardItemType: "wolf_fang",
      rewardItemImg: "/assets/items/wolf-fang.png",
      rewardItemEffect: "Trofeu de caca",
      rewardItemValue: 40,
      rewardItemQuantity: 1,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 7),
    },
    {
      title: "Queda do Cavaleiro Corrompido",
      description: "Derrube o guardiao amaldiçoado que protege a muralha antiga.",
      monsterName: "Cavaleiro Corrompido",
      recommendedLevel: 15,
      difficulty: GameplayDifficulty.HARD,
      reward: 520,
      rewardXp: 340,
      rewardItemName: "Nucleo Corrompido",
      rewardItemCategory: "monster_drop",
      rewardItemType: "corrupted_core",
      rewardItemImg: "/assets/items/corrupted-core.png",
      rewardItemEffect: "Fragmento de energia sombria",
      rewardItemValue: 180,
      rewardItemQuantity: 1,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
    },
    {
      title: "Caca ao Drake de Obsidiana",
      description: "Interrompa a rota de destruição do drake antes que ele alcance a fortaleza.",
      monsterName: "Drake de Obsidiana",
      recommendedLevel: 30,
      difficulty: GameplayDifficulty.ELITE,
      reward: 1480,
      rewardXp: 980,
      rewardItemName: "Escama de Obsidiana",
      rewardItemCategory: "monster_drop",
      rewardItemType: "obsidian_scale",
      rewardItemImg: "/assets/items/obsidian-scale.png",
      rewardItemEffect: "Material raro de forja pesada",
      rewardItemValue: 420,
      rewardItemQuantity: 1,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 14),
    },
    {
      title: "Execucao do Titã do Vazio",
      description: "Mobilize a ofensiva final para abater a criatura que distorce o campo de batalha.",
      monsterName: "Titã do Vazio",
      recommendedLevel: 50,
      difficulty: GameplayDifficulty.ELITE,
      reward: 4200,
      rewardXp: 2600,
      rewardItemName: "Fragmento do Vazio",
      rewardItemCategory: "monster_drop",
      rewardItemType: "void_fragment",
      rewardItemImg: "/assets/items/void-fragment.png",
      rewardItemEffect: "Residuo de uma entidade colossal",
      rewardItemValue: 1200,
      rewardItemQuantity: 1,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 21),
    },
    {
      title: "Awaken",
      description: "Derrote o Avatar do Despertar para conquistar o emblema necessario para evoluir sua classe base.",
      monsterName: "Avatar do Despertar",
      recommendedLevel: 30,
      difficulty: GameplayDifficulty.ELITE,
      reward: 1800,
      rewardXp: 1200,
      rewardItemName: "Emblema do Despertar",
      rewardItemCategory: "special",
      rewardItemType: "awakening_token",
      rewardItemImg: "/assets/items/awakening-emblem.png",
      rewardItemEffect: "Catalisador usado no awaken de classe",
      rewardItemValue: 0,
      rewardItemQuantity: 1,
      status: "OPEN",
      timeLimit: new Date(Date.now() + 1000 * 60 * 60 * 24 * 30),
    },
  ];

  for (const bounty of bounties) {
    const monster = createdMonsters.find((entry) => entry.name === bounty.monsterName);

    if (!monster) {
      continue;
    }

    const existingBounty = await prisma.bountyHunt.findFirst({
      where: {
        title: bounty.title,
      },
    });

    if (existingBounty) {
      await prisma.bountyHunt.update({
        where: { id: existingBounty.id },
        data: {
          title: bounty.title,
          description: bounty.description,
          monsterId: monster.id,
          recommendedLevel: bounty.recommendedLevel,
          difficulty: bounty.difficulty,
          reward: bounty.reward,
          rewardXp: bounty.rewardXp,
          rewardItemName: bounty.rewardItemName,
          rewardItemCategory: bounty.rewardItemCategory,
          rewardItemType: bounty.rewardItemType,
          rewardItemImg: bounty.rewardItemImg,
          rewardItemEffect: bounty.rewardItemEffect,
          rewardItemValue: bounty.rewardItemValue,
          rewardItemQuantity: bounty.rewardItemQuantity ?? 1,
          timeLimit: bounty.timeLimit,
          isActive: true,
          status: bounty.status,
        },
      });
    } else {
      await prisma.bountyHunt.create({
        data: {
          title: bounty.title,
          description: bounty.description,
          monsterId: monster.id,
          recommendedLevel: bounty.recommendedLevel,
          difficulty: bounty.difficulty,
          reward: bounty.reward,
          rewardXp: bounty.rewardXp,
          rewardItemName: bounty.rewardItemName,
          rewardItemCategory: bounty.rewardItemCategory,
          rewardItemType: bounty.rewardItemType,
          rewardItemImg: bounty.rewardItemImg,
          rewardItemEffect: bounty.rewardItemEffect,
          rewardItemValue: bounty.rewardItemValue,
          rewardItemQuantity: bounty.rewardItemQuantity ?? 1,
          status: bounty.status,
          timeLimit: bounty.timeLimit,
          isActive: true,
        },
      });
    }
  }

  const missions = [
    {
      title: "Patrulha da Estrada Velha",
      description: "Missao introdutoria para limpar a via principal.",
      difficulty: GameplayDifficulty.EASY,
      recommendedLevel: 1,
      enemyName: "Bandido Isolado",
      enemyLevel: 1,
      enemyHealth: 45,
      enemyAttack: 9,
      enemyDefense: 4,
      rewardXp: 30,
      rewardCoins: 18,
    },
    {
      title: "Ruinas do Vigia",
      description: "Confronto intermediario em uma area hostil.",
      difficulty: GameplayDifficulty.MEDIUM,
      recommendedLevel: 3,
      enemyName: "Guardiao das Ruinas",
      enemyLevel: 4,
      enemyHealth: 80,
      enemyAttack: 16,
      enemyDefense: 8,
      rewardXp: 70,
      rewardCoins: 40,
    },
    {
      title: "Cerco do Forte",
      description: "Missao avancada com premio de coleta.",
      difficulty: GameplayDifficulty.HARD,
      recommendedLevel: 5,
      enemyName: "Capitao Invasor",
      enemyLevel: 6,
      enemyHealth: 110,
      enemyAttack: 22,
      enemyDefense: 11,
      rewardXp: 120,
      rewardCoins: 75,
      rewardItemName: "Insignia do Forte",
      rewardItemCategory: "quest",
      rewardItemType: "fort_badge",
      rewardItemImg: "/assets/items/fort-badge.png",
      rewardItemEffect: "Comprovante de missao",
      rewardItemValue: 55,
      rewardItemQuantity: 1,
    },
    {
      title: "Assalto ao Arsenal Quebrado",
      description: "Recupere o posto avançado tomado por veteranos renegados.",
      difficulty: GameplayDifficulty.HARD,
      recommendedLevel: 20,
      enemyName: "Capitao da Ruina",
      enemyLevel: 22,
      enemyHealth: 320,
      enemyAttack: 52,
      enemyDefense: 24,
      rewardXp: 420,
      rewardCoins: 260,
      rewardItemName: "Selo do Arsenal",
      rewardItemCategory: "quest",
      rewardItemType: "arsenal_seal",
      rewardItemImg: "/assets/items/arsenal-seal.png",
      rewardItemEffect: "Prova de conquista militar",
      rewardItemValue: 160,
      rewardItemQuantity: 1,
    },
    {
      title: "Ruptura do Bastiao Rubro",
      description: "Abra caminho pelo bastiao incendiado e neutralize a guarnição de elite.",
      difficulty: GameplayDifficulty.ELITE,
      recommendedLevel: 30,
      enemyName: "General Rubro",
      enemyLevel: 32,
      enemyHealth: 560,
      enemyAttack: 88,
      enemyDefense: 38,
      rewardXp: 960,
      rewardCoins: 620,
      rewardItemName: "Insignia Rubra",
      rewardItemCategory: "quest",
      rewardItemType: "crimson_insignia",
      rewardItemImg: "/assets/items/crimson-insignia.png",
      rewardItemEffect: "Marca de comando conquistada em batalha",
      rewardItemValue: 420,
      rewardItemQuantity: 1,
    },
    {
      title: "Trono das Cinzas Eternas",
      description: "Enfrente o soberano das cinzas no interior da fortaleza devastada.",
      difficulty: GameplayDifficulty.ELITE,
      recommendedLevel: 40,
      enemyName: "Rei das Cinzas",
      enemyLevel: 42,
      enemyHealth: 880,
      enemyAttack: 126,
      enemyDefense: 54,
      rewardXp: 1680,
      rewardCoins: 1100,
      rewardItemName: "Coroa Carbonizada",
      rewardItemCategory: "quest",
      rewardItemType: "ashen_crown",
      rewardItemImg: "/assets/items/ashen-crown.png",
      rewardItemEffect: "Trofeu da campanha final",
      rewardItemValue: 760,
      rewardItemQuantity: 1,
    },
  ];

  for (const mission of missions) {
    const existingMission = await prisma.missionDefinition.findFirst({
      where: { title: mission.title },
    });

    if (existingMission) {
      await prisma.missionDefinition.update({
        where: { id: existingMission.id },
        data: {
          ...mission,
          isActive: true,
          rewardItemQuantity: mission.rewardItemQuantity ?? 1,
        },
      });
    } else {
      await prisma.missionDefinition.create({
        data: {
          ...mission,
          isActive: true,
          rewardItemQuantity: mission.rewardItemQuantity ?? 1,
        },
      });
    }
  }

  const trainings = [
    {
      name: "Treino de Forca Basico",
      description: "Sessao curta para aumentar a eficiencia ofensiva.",
      trainingType: "strength",
      xpReward: 30,
      coinsReward: 5,
      cooldownSeconds: 3600,
    },
    {
      name: "Estudo Arcano Guiado",
      description: "Sessao de concentracao e leitura de grimorios.",
      trainingType: "intelligence",
      xpReward: 34,
      coinsReward: 5,
      cooldownSeconds: 3600,
    },
    {
      name: "Circuito de Agilidade",
      description: "Treino de movimentacao e reflexo.",
      trainingType: "dexterity",
      xpReward: 32,
      coinsReward: 6,
      cooldownSeconds: 3600,
    },
  ];

  for (const training of trainings) {
    const existingTraining = await prisma.trainingDefinition.findFirst({
      where: { name: training.name },
    });

    if (existingTraining) {
      await prisma.trainingDefinition.update({
        where: { id: existingTraining.id },
        data: {
          ...training,
          isActive: true,
        },
      });
    } else {
      await prisma.trainingDefinition.create({
        data: {
          ...training,
          isActive: true,
        },
      });
    }
  }

  const npcs = [
    {
      name: "Mestre Rowan",
      role: "mentor",
      interactionType: "mentor",
      description: "Instrutor de combate para aventureiros iniciantes.",
      dialogue: "Disciplina e repeticao vencem batalhas longas.",
      xpReward: 28,
      coinsReward: 0,
    },
    {
      name: "Selma Mercadora",
      role: "merchant",
      interactionType: "merchant",
      description: "Negociante de rotas e suprimentos.",
      dialogue: "Informacao certa sempre vale moedas.",
      xpReward: 0,
      coinsReward: 18,
    },
    {
      name: "Irmã Elise",
      role: "healer",
      interactionType: "healer",
      description: "Curandeira de campo que ajuda viajantes.",
      dialogue: "Leve este kit e volte inteiro.",
      xpReward: 12,
      coinsReward: 0,
      rewardItemName: "Pocao de Campo",
      rewardItemCategory: "consumable",
      rewardItemType: "field_supply",
      rewardItemImg: "/assets/items/field-potion.png",
      rewardItemEffect: "Suprimento de viagem",
      rewardItemValue: 20,
      rewardItemQuantity: 1,
    },
    {
      name: "Arcanista Lyra",
      role: "buffer",
      interactionType: "buffer",
      description: "Encantadora que fortalece aventureiros por uma taxa em gold.",
      dialogue: "Escolha a intensidade do encantamento: 2%, 4% ou 6%. Quanto maior o poder, maior o custo.",
      xpReward: 0,
      coinsReward: 0,
    },
  ];

  for (const npc of npcs) {
    const existingNpc = await prisma.npcDefinition.findFirst({
      where: {
        name: npc.name,
        interactionType: npc.interactionType,
      },
    });

    if (existingNpc) {
      await prisma.npcDefinition.update({
        where: { id: existingNpc.id },
        data: {
          ...npc,
          isActive: true,
          rewardItemQuantity: npc.rewardItemQuantity ?? 1,
        },
      });
    } else {
      await prisma.npcDefinition.create({
        data: {
          ...npc,
          isActive: true,
          rewardItemQuantity: npc.rewardItemQuantity ?? 1,
        },
      });
    }
  }

  const products = [
    {
      slug: "small-health-potion",
      name: "Pocao Pequena de Vida",
      description: "Consumivel para recuperar vida.",
      category: "consumable",
      type: "healing",
      img: "/assets/items/potion-small.png",
      effect: "+50 HP",
      assetKind: ShopProductAssetKind.ITEM,
      price: 25,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "coin-pack-1000",
      name: "Pacote de 1000 Coins",
      description: "Credito premium para gastar na loja do jogo.",
      category: "currency",
      type: "coin_pack",
      img: "/assets/items/coin-pack-1000.png",
      effect: "1000 coins",
      assetKind: ShopProductAssetKind.COINS,
      price: 1990,
      rewardCoins: 1000,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-1-blade",
      name: "Lamina do Recruta",
      description: "Equipamento Tier 1 para quem esta entrando nos primeiros combates.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-1-blade.png",
      effect: "+4 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 80,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-1-armor",
      name: "Armadura do Recruta",
      description: "Protecao Tier 1 com foco em sobrevivencia basica.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-1-armor.png",
      effect: "+6 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 75,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-1-charm",
      name: "Talisma do Recruta",
      description: "Acessorio Tier 1 para estabilizar a postura defensiva.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-1-charm.png",
      effect: "+2 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 70,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-2-blade",
      name: "Lamina do Guarda",
      description: "Equipamento Tier 2 para patrulhas e cacas moderadas.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-2-blade.png",
      effect: "+7 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 160,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-2-armor",
      name: "Armadura do Guarda",
      description: "Protecao Tier 2 para jornadas mais longas.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-2-armor.png",
      effect: "+12 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 150,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-2-charm",
      name: "Talisma do Guarda",
      description: "Acessorio Tier 2 que reforca a defesa no combate.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-2-charm.png",
      effect: "+4 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 145,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-3-blade",
      name: "Lamina do Veterano",
      description: "Equipamento Tier 3 com dano consistente para missoes medias.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-3-blade.png",
      effect: "+11 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 290,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-3-armor",
      name: "Armadura do Veterano",
      description: "Protecao Tier 3 para personagens que ja sustentam trocas longas.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-3-armor.png",
      effect: "+20 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 270,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-3-charm",
      name: "Talisma do Veterano",
      description: "Acessorio Tier 3 para consolidar uma linha de frente robusta.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-3-charm.png",
      effect: "+6 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 260,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-3-crit-charm",
      name: "Sigilo do Caçador",
      description: "Acessorio focado em aumentar a chance de acerto critico em conteudo intermediario.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-3-crit-charm.png",
      effect: "+3 CRIT",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 310,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-4-blade",
      name: "Lamina do Campeao",
      description: "Equipamento Tier 4 para conteudo de alta pressao.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-4-blade.png",
      effect: "+15 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 480,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-4-armor",
      name: "Armadura do Campeao",
      description: "Protecao Tier 4 para encontros de risco elevado.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-4-armor.png",
      effect: "+30 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 455,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-4-charm",
      name: "Talisma do Campeao",
      description: "Acessorio Tier 4 feito para lutas de elite.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-4-charm.png",
      effect: "+9 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 430,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-5-blade",
      name: "Lamina do Soberano",
      description: "Equipamento Tier 5 para o topo da progressao.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-5-blade.png",
      effect: "+20 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 760,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-5-armor",
      name: "Armadura do Soberano",
      description: "Protecao Tier 5 para suportar os encontros finais.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-5-armor.png",
      effect: "+42 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 720,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-5-charm",
      name: "Talisma do Soberano",
      description: "Acessorio Tier 5 para compor builds de fim de jogo.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-5-charm.png",
      effect: "+12 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 690,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-5-crit-charm",
      name: "Olho da Emboscada",
      description: "Acessorio high-tier para builds voltadas a burst e finalizacao rapida.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-5-crit-charm.png",
      effect: "+5 CRIT",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 810,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-6-blade",
      name: "Lamina do Abismo",
      description: "Equipamento Tier 6 para personagens em conteudo de nivel 20+.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-6-blade.png",
      effect: "+28 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1180,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-6-armor",
      name: "Armadura do Abismo",
      description: "Protecao Tier 6 para sustentar combates agressivos de midgame alto.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-6-armor.png",
      effect: "+58 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1120,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-6-charm",
      name: "Talisma do Abismo",
      description: "Acessorio Tier 6 para reforco defensivo em patrulhas perigosas.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-6-charm.png",
      effect: "+16 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1080,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-7-blade",
      name: "Lamina Celestial",
      description: "Equipamento Tier 7 preparado para confrontos de nivel 30+.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-7-blade.png",
      effect: "+38 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1860,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-7-armor",
      name: "Armadura Celestial",
      description: "Protecao Tier 7 para raids e linhas de frente pesadas.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-7-armor.png",
      effect: "+82 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1780,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-7-charm",
      name: "Talisma Celestial",
      description: "Acessorio Tier 7 feito para estabilizar confrontos de elite.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-7-charm.png",
      effect: "+22 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 1710,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-blade",
      name: "Lamina do Eclipse",
      description: "Equipamento Tier 8 para o conteudo mais extremo da progressao.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-8-blade.png",
      effect: "+52 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 2920,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-armor",
      name: "Armadura do Eclipse",
      description: "Protecao Tier 8 para enfrentar entidades de nivel 40+ e chefes finais.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-8-armor.png",
      effect: "+118 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 2810,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-charm",
      name: "Talisma do Eclipse",
      description: "Acessorio Tier 8 para builds voltadas ao endgame pesado.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-8-charm.png",
      effect: "+30 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 2680,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-void-blade",
      name: "Lamina da Ruptura",
      description: "Arma Tier 8 de alto risco: amplia criticos ao custo de vitalidade.",
      category: "weapon",
      type: "weapon",
      img: "/assets/items/tier-8-void-blade.png",
      effect: "+8 CRIT -40 HP",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 3180,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-void-armor",
      name: "Armadura do Sacrificio",
      description: "Armadura Tier 8 focada em defesa brutal com sacrificio ofensivo.",
      category: "armor",
      type: "armor",
      img: "/assets/items/tier-8-void-armor.png",
      effect: "+24 DEF -12 ATK",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 3090,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-void-charm",
      name: "Sigilo da Entropia",
      description: "Charm Tier 8 para burst extremo com custo em estabilidade defensiva.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-8-void-charm.png",
      effect: "+10 CRIT +12 ATK -16 DEF",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 3260,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
    {
      slug: "tier-8-crit-charm",
      name: "Foco do Predador Astral",
      description: "Acessorio de endgame para maximizar a frequencia de criticos em lutas longas.",
      category: "accessory",
      type: "accessory",
      img: "/assets/items/tier-8-crit-charm.png",
      effect: "+8 CRIT",
      assetKind: ShopProductAssetKind.EQUIPMENT,
      price: 3010,
      rewardCoins: 0,
      rewardQuantity: 1,
      currency: "BRL",
      isActive: true,
    },
  ];

  for (const product of products) {
    await prisma.shopProduct.upsert({
      where: { slug: product.slug },
      update: product,
      create: product,
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
