-- AlterTable
ALTER TABLE "Character" ADD COLUMN     "lastCheckpoint" TEXT,
ADD COLUMN     "posX" DOUBLE PRECISION,
ADD COLUMN     "posY" DOUBLE PRECISION,
ADD COLUMN     "posZ" DOUBLE PRECISION,
ADD COLUMN     "xp" INTEGER NOT NULL DEFAULT 0;
