import { CharacterBuilderConfig } from "./builder.types";

export const PILOT_V1_BUILDER_CONFIG: CharacterBuilderConfig = {
  version: "pilot-v1",
  status: "APPROVED",
  approvedBy: "PRODUCT_OWNER",
  scope: [
    "public_campaign_entry",
    "character_creation",
    "player_ai_assistance",
    "final_participant_survey",
  ],
  archetypes: {
    classification: "RULE",
    selection: { exact: 1 },
    options: [
      { key: "guardian_blade", name: "Guardiao da Lamina" },
      { key: "guardian_shield", name: "Guardiao do Escudo" },
      { key: "guardian_oracle", name: "Guardiao do Oraculo" },
      { key: "guardian_flames", name: "Guardiao das Chamas" },
      { key: "guardian_hunt", name: "Guardiao da Caca" },
      { key: "guardian_souls", name: "Guardiao das Almas" },
      { key: "guardian_wanderer", name: "Guardiao Errante" },
    ],
    sourceNotes: [
      "Descricoes, atributos relacionados e habilidades iniciais devem ser extraidos do Manual do Jogador.",
      "O frontend nao deve duplicar ou reinterpretar essas regras.",
    ],
  },
  attributes: {
    classification: "RULE",
    totalPoints: 12,
    minValue: 0,
    maxInitialWithoutApproval: 4,
    pilotSelectableMax: 4,
    requireAtLeastOneOf: [{ keys: ["vigor", "spirit"], minValue: 1 }],
    options: [
      { key: "strength", name: "Forca", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
      { key: "agility", name: "Agilidade", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
      { key: "vigor", name: "Vigor", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
      { key: "intellect", name: "Intelecto", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
      { key: "presence", name: "Presenca", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
      { key: "spirit", name: "Espirito", min: 0, maxInitialWithoutApproval: 4, pilotSelectableMax: 4 },
    ],
    derivedResources: [
      { key: "hp", name: "PV", backendCalculated: true, formula: "10 + vigor * 4" },
      { key: "energy", name: "Energia", backendCalculated: true, formula: "6 + vigor + spirit" },
      { key: "ascensionPoints", name: "Pontos de Ascensao", backendCalculated: true, formula: "2 + spirit" },
    ],
  },
  trainings: {
    classification: "RULE",
    selection: { exact: 3, distinct: true },
    bonus: 2,
    options: [
      { key: "combat", name: "Combate" },
      { key: "defense", name: "Defesa" },
      { key: "survival", name: "Sobrevivencia" },
      { key: "investigation", name: "Investigacao" },
      { key: "influence", name: "Influencia" },
      { key: "stealth", name: "Furtividade" },
      { key: "healing", name: "Cura" },
      { key: "spirituality", name: "Espiritualidade" },
      { key: "craft", name: "Oficio" },
    ],
  },
  traitsAndBond: {
    classification: "RULE_AND_PRODUCT_DECISION",
    required: {
      positiveTrait: true,
      negativeTrait: true,
      narrativeBond: true,
    },
    suggestedPositiveTraits: [
      { value: "Esperanca de Bravantus" },
      { value: "Sangue Frio na Muralha" },
      { value: "Voz que Inspira" },
      { value: "Olhos de Cacador" },
    ],
    suggestedNegativeTraits: [
      { value: "Peso da Alma Antiga" },
      { value: "Medo da Ascensao" },
      { value: "Marca Instavel" },
      { value: "Culpa de Sobrevivente" },
    ],
    suggestedBonds: [
      { value: "Irma em Bravantus" },
      { value: "Juramento ao Salao" },
      { value: "Divida com o Xama" },
      { value: "Promessa a um soldado morto" },
    ],
    rules: [
      "O jogador pode selecionar uma sugestao ou escrever uma opcao propria.",
      "Cada campo e obrigatorio.",
      "Opcoes personalizadas continuam como rascunho do jogador.",
      "A IA pode sugerir redacoes, mas nao preencher nem confirmar automaticamente.",
      "O Mestre pode aceitar ou solicitar ajuste.",
      "A IA nao pode transformar uma Trait ou vinculo em canon oficial.",
    ],
  },
  equipment: {
    classification: "RULE_AND_PRODUCT_DECISION",
    minInitialItems: 1,
    slots: [
      { key: "main_hand", name: "Mao principal" },
      { key: "off_hand", name: "Mao secundaria" },
      { key: "armor", name: "Armadura" },
      { key: "boots", name: "Botas" },
      { key: "belt", name: "Cinto" },
      { key: "amulet", name: "Colar ou amuleto" },
      { key: "relic", name: "Reliquia" },
      { key: "quick_consumable", name: "Consumivel rapido" },
    ],
    rules: [
      "Cada slot recebe no maximo um item.",
      "O personagem precisa possuir pelo menos um item inicial.",
      "Os itens documentados no Manual aparecem como sugestoes.",
      "O jogador pode descrever um item comum proprio.",
      "Itens personalizados nao recebem bonus automaticamente.",
      "Reliquias e itens especiais exigem aprovacao do Mestre.",
      "Bonus, dano ou habilidade somente podem ser aplicados quando definidos no Manual ou aprovados pelo Mestre.",
      "Combate e execucao dos efeitos dos equipamentos permanecem fora deste MVP.",
    ],
  },
  episodeQuestions: {
    classification: "PUBLIC_CANON_AND_RULE",
    requiredBeforeSubmission: true,
    questions: [
      {
        questionKey: "relationship_with_erya",
        version: "pilot-v1",
        prompt: "Qual e sua relacao com Erya?",
        required: true,
      },
      {
        questionKey: "protection_in_bravantus",
        version: "pilot-v1",
        prompt: "Quem ou o que voce deseja proteger em Bravantus?",
        required: true,
      },
      {
        questionKey: "past_connection_to_mandukuru",
        version: "pilot-v1",
        prompt: "Qual acontecimento do seu passado pode estar ligado a Mandukuru?",
        required: true,
      },
      {
        questionKey: "fear_of_guardian_souls",
        version: "pilot-v1",
        prompt: "Por que voce teme ou desconfia das almas dos Guardioes?",
        required: true,
      },
    ],
    rules: [
      "As questionKey sao estaveis.",
      "Alteracoes futuras no texto nao alteram a chave.",
      "Cada resposta registra a versao da pergunta.",
      "As respostas pertencem ao jogador e ficam disponiveis ao Mestre apos o envio.",
      "A IA pode usar as respostas para sugerir possibilidades.",
      "A IA nao pode declarar que uma ligacao e verdadeira.",
      "A IA nao pode inventar segredo, alterar o passado ou revelar informacoes sobre Zurich.",
    ],
  },
  aiBoundaries: [
    "A IA sugere; o jogador decide.",
    "Nenhuma sugestao pode alterar a ficha automaticamente.",
    "Nenhum conteudo secreto pode ser enviado ao jogador.",
    "A IA nao pode inventar segredo, alterar o passado ou revelar informacoes sobre Zurich.",
  ],
};

export const OFFICIAL_BUILDER_CONFIGS = {
  "pilot-v1": PILOT_V1_BUILDER_CONFIG,
} as const;
